version: "3.0"

services:
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8088:80

  frontend:
    container_name: "frontend"
    restart: always
    build:
      context: ./frontend
    environment:
      GENERATE_SOURCEMAP: "false"
      WDS_SOCKET_PORT: 0
    command: npm start

  backend:
    container_name: "backend"
    build:
      context: ./backend/backend
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: mongo123
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_NAME: goldenaxe
      EXTERNAL_HOST: 10.78.127.179
      SFTP_PORT: 22
      SFTP_USER: sftp
      SFTP_PASSWORD: sftp
      SFTP_PATH: /srv/backup

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: goldenaxe
    volumes:
      - mongodb-integration-vol:/data/db

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123

volumes:
  mongodb-integration-vol:
