services:
  backend:
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: mongo123
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_NAME: goldenaxe
      EXTERNAL_HOST: 10.78.127.179
      SFTP_PORT: 22
      SFTP_USER: sftp
      SFTP_PASSWORD: "goldenaxe123!"
      SFTP_PATH: /srv/backup
    ports:
      - 8000:8000

  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: goldenaxe
    volumes:
      - mongodb-vol:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123
volumes:
  mongodb-vol: